
export const DictPL485Dev = [
  {
    name: "红料1配料螺旋-电流",
    formatter: "current",
    field: "hf1_pllx_current",
    type: "REAL",
    permission: "R",
  },
  {
    name: "红料2配料螺旋-电流",
    formatter: "current",
    field: "hf2_pllx_current",
    type: "REAL",
    permission: "R",
  },
  {
    name: "红料3配料螺旋-电流",
    formatter: "current",
    field: "hf3pllx_current",
    type: "REAL",
    permission: "R",
  },
  {
    name: "红料4配料螺旋-电流",
    formatter: "current",
    field: "hf4_pllx_current",
    type: "REAL",
    permission: "R",
  },
  {
    name: "红料1配料螺旋-频率",
    field: "hf1_pllx_freq",
    type: "REAL",
    permission: "R",
    cmd: "hf1GllxFreqSet",
  },
  {
    name: "红料2配料螺旋-频率",
    field: "hf2_pllx_freq",
    type: "REAL",
    permission: "R",
    cmd: "hf2GllxFreqSet",
  },
  {
    name: "红料3配料螺旋-频率",
    field: "hf3_pllx_freq",
    type: "REAL",
    permission: "R",
    cmd: "hf3GllxFreqSet",
  },
  {
    name: "红料4配料螺旋-频率",
    field: "hf4_pllx_freq",
    type: "REAL",
    permission: "R",
    cmd: "hf4GllxFreqSet",
  },
];

export const DictPLPlc = [
  {
    name: "红料1上料螺旋-运行",
    field: "HF1_SLLX_Sta",
    internal: "I0.0",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉1上料提升-运行",
    field: "HF1_SLTS_Sta",
    internal: "I0.1",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉1传输螺旋-运行",
    field: "HF1_CSLX_Sta",
    internal: "I0.2",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红料2上料螺旋-运行",
    field: "HF2_SLLX_Sta",
    internal: "I0.3",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉2上料提升-运行",
    field: "HF2_SLTS_Sta",
    internal: "I0.4",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉2传输螺旋-运行",
    field: "HF2_CSLX_Sta",
    internal: "I0.5",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红料3上料螺旋-运行",
    field: "HF3_SLLX_Sta",
    internal: "I0.6",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉3上料提升-运行",
    field: "HF3_SLTS_Sta",
    internal: "I0.7",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉3传输螺旋-运行",
    field: "HF3_CSLX_Sta",
    internal: "I1.0",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红料4上料螺旋-运行",
    field: "HF4_SLLX_Sta",
    internal: "I1.1",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉4上料提升-运行",
    field: "HF4_SLTS_Sta",
    internal: "I1.2",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉4传输螺旋-运行",
    field: "HF4_CSLX_Sta",
    internal: "I1.3",
    type: "BIT",
    permission: "R",
  },
  {
    name: "小料螺旋-运行",
    field: "XLLX_Sta",
    internal: "I1.4",
    type: "BIT",
    permission: "R",
  },
  {
    name: "犁刀机-运行",
    field: "LDJ_Sta",
    internal: "I1.5",
    type: "BIT",
    permission: "R",
  },
  {
    name: "小飞刀-运行",
    field: "XFD_Sta",
    internal: "I1.6",
    type: "BIT",
    permission: "R",
  },
  {
    name: "大计量斗电磁阀-运行",
    field: "DJLDDCF_Sta",
    internal: "I1.7",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红料1上料螺旋-故障",
    field: "HF1_SLLX_Err",
    internal: "I2.0",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉1上料提升-故障",
    field: "HF1_SLTS_Err",
    internal: "I2.1",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉1传输螺旋-故障",
    field: "HF1_CSLX_Err",
    internal: "I2.2",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红料2上料螺旋-故障",
    field: "HF2_SLLX_Err",
    internal: "I2.3",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉2上料提升-故障",
    field: "HF2_SLTS_Err",
    internal: "I2.4",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉2传输螺旋-故障",
    field: "HF2_CSLX_Err",
    internal: "I2.5",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红料3上料螺旋-故障",
    field: "HF3_SLLX_Err",
    internal: "I2.6",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉3上料提升-故障",
    field: "HF3_SLTS_Err",
    internal: "I2.7",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉3传输螺旋-故障",
    field: "HF3_CSLX_Err",
    internal: "I3.0",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红料4上料螺旋-故障",
    field: "HF4_SLLX_Err",
    internal: "I3.1",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉4上料提升-故障",
    field: "HF4_SLTS_Err",
    internal: "I3.2",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉4传输螺旋-故障",
    field: "HF4_CSLX_Err",
    internal: "I3.3",
    type: "BIT",
    permission: "R",
  },
  {
    name: "小料螺旋-故障",
    field: "XLLX_Err",
    internal: "I3.4",
    type: "BIT",
    permission: "R",
  },
  {
    name: "犁刀机-故障",
    field: "LDJ_Err",
    internal: "I3.5",
    type: "BIT",
    permission: "R",
  },
  {
    name: "小飞刀-故障",
    field: "XFD_Err",
    internal: "I3.6",
    type: "BIT",
    permission: "R",
  },
  {
    name: "混料机卸料电磁阀-运行",
    field: "HLJXLDCF_Sta",
    internal: "I3.7",
    type: "BIT",
    permission: "R",
  },
  // {
  //   name: "计量斗电振机-故障",
  //   field: "JLDDZJ_Err",
  //   internal: "I4.0",
  //   type: "BIT",
  //   permission: "R",
  // },
  { name: "A8报警", field: "A8_Err", internal: "I4.1", type: "BIT", permission: "R" },
  {
    name: "物料慢加-运行",
    field: "WLMJ_Sta",
    internal: "I4.2",
    type: "BIT",
    permission: "R",
  },
  {
    name: "物料快加-运行",
    field: "WLKJ_Sta",
    internal: "I4.3",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉1电震-故障",
    field: "HF1_DZJ_Err",
    internal: "I8.0",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉2电震-故障",
    field: "HF2_DZJ_Err",
    internal: "I8.1",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉3电震-故障",
    field: "HF3_DZJ_Err",
    internal: "I8.2",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉4电震-故障",
    field: "HF4_DZJ_Err",
    internal: "I8.3",
    type: "BIT",
    permission: "R",
  },
  {
    name: "计量斗电震-故障",
    field: "JLDDZJ_Err",
    internal: "I8.4",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉1电震机-输出",
    field: "HF1_DZJ_Output",
    internal: "Q0.0",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉1电震机-输出",
    field: "HF2_DZJ_Output",
    internal: "Q0.1",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉1电震机-输出",
    field: "HF3_DZJ_Output",
    internal: "Q0.2",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红粉1电震机-输出",
    field: "HF4_DZJ_Output",
    internal: "Q0.3",
    type: "BIT",
    permission: "R",
  },
  {
    name: "混料时间控制-输出",
    field: "HLSJ_Ctrl_Output",
    internal: "Q0.4",
    type: "BIT",
    permission: "R",
  },
  {
    name: "小计量斗卸料阀-输出",
    field: "XJLD_XLF_Output",
    internal: "Q0.5",
    type: "BIT",
    permission: "R",
  },
  {
    name: "犁刀机控制-输出",
    field: "LDJ_Output",
    internal: "Q0.6",
    type: "BIT",
    permission: "R",
  },
  {
    name: "红料1上料螺旋-电流",
    formatter: "current",
    field: "HF1_SLLX_Current",
    internal: "VD22",
    type: "REAL",
    permission: "R",
  },
  {
    name: "红粉1上料提升-电流",
    formatter: "current",
    field: "HF1_SLTS_Current",
    internal: "VD26",
    type: "REAL",
    permission: "R",
  },
  {
    name: "红粉1传输螺旋-电流",
    formatter: "current",
    field: "HF1_CSLX_Current",
    internal: "VD30",
    type: "REAL",
    permission: "R",
  },
  {
    name: "红料2上料螺旋-电流",
    formatter: "current",
    field: "HF2_SLLX_Current",
    internal: "VD34",
    type: "REAL",
    permission: "R",
  },
  {
    name: "红粉2上料提升-电流",
    formatter: "current",
    field: "HF2_SLTS_Current",
    internal: "VD38",
    type: "REAL",
    permission: "R",
  },
  {
    name: "红粉2传输螺旋-电流",
    formatter: "current",
    field: "HF2_CSLX_Current",
    internal: "VD42",
    type: "REAL",
    permission: "R",
  },
  {
    name: "红料3上料螺旋-电流",
    formatter: "current",
    field: "HF3_SLLX_Current",
    internal: "VD46",
    type: "REAL",
    permission: "R",
  },
  {
    name: "红粉3上料提升-电流",
    formatter: "current",
    field: "HF3_SLTS_Current",
    internal: "VD50",
    type: "REAL",
    permission: "R",
  },
  {
    name: "红粉3传输螺旋-电流",
    formatter: "current",
    field: "HF3_CSLX_Current",
    internal: "VD54",
    type: "REAL",
    permission: "R",
  },
  {
    name: "红料4上料螺旋-电流",
    formatter: "current",
    field: "HF4_SLLX_Current",
    internal: "VD58",
    type: "REAL",
    permission: "R",
  },
  {
    name: "红粉4上料提升-电流",
    formatter: "current",
    field: "HF4_SLTS_Current",
    internal: "VD62",
    type: "REAL",
    permission: "R",
  },
  {
    name: "红粉4传输螺旋-电流",
    formatter: "current",
    field: "HF4_CSLX_Current",
    internal: "VD66",
    type: "REAL",
    permission: "R",
  },
  {
    name: "小料配料-电流",
    formatter: "current",
    field: "XLLX_Current",
    internal: "VD70",
    type: "REAL",
    permission: "R",
  },
  {
    name: "犁刀机-电流",
    formatter: "current",
    field: "LDJ_Current",
    internal: "VD74",
    type: "REAL",
    permission: "R",
  },
  {
    name: "小飞刀-电流",
    formatter: "current",
    field: "XFD_Current",
    internal: "VD78",
    type: "REAL",
    permission: "R",
  },
  {
    name: "混料计时器-状态",
    field: "HLJSQ_Sta",
    internal: "M1.1",
    type: "BIT",
    permission: "R",
  },
  {
    name: "混料计时器-工作时长设置",
    field: "HLJSQ_Work_Tim_Set",
    internal: "VW2",
    type: "WORD",
    permission: "R/D",
  },
  {
    name: "红粉1电震机-最大定时-设置",
    field: "HF1_DZJ_TIM_MAX_Set",
    internal: "VW6",
    type: "WORD",
    permission: "R/D",
  },
  {
    name: "红粉1电震机-震动时间-设置",
    field: "HF1_DZJ_TIM_Set",
    internal: "VW8",
    type: "WORD",
    permission: "R/D",
  },
  {
    name: "红粉2电震机-最大定时-设置",
    field: "HF2_DZJ_TIM_MAX_Set",
    internal: "VW10",
    type: "WORD",
    permission: "R/D",
  },
  {
    name: "红粉2电震机-震动时间-设置",
    field: "HF2_DZJ_TIM_Set",
    internal: "VW12",
    type: "WORD",
    permission: "R/D",
  },
  {
    name: "红粉3电震机-最大定时-设置",
    field: "HF3_DZJ_TIM_MAX_Set",
    internal: "VW14",
    type: "WORD",
    permission: "R/D",
  },
  {
    name: "红粉3电震机-震动时间-设置",
    field: "HF3_DZJ_TIM_Set",
    internal: "VW16",
    type: "WORD",
    permission: "R/D",
  },
  {
    name: "红粉4电震机-最大定时-设置",
    field: "HF4_DZJ_TIM_MAX_Set",
    internal: "VW18",
    type: "WORD",
    permission: "R/D",
  },
  {
    name: "红粉4电震机-震动时间-设置",
    field: "HF4_DZJ_TIM_Set",
    internal: "VW20",
    type: "WORD",
    permission: "R/D",
  },
];

export const DictPLA8 = [
  { "name": "红粉1加料百分比", "field": "P1", "permission": "R", "type": "FLOAT" }, { "name": "红粉2加料百分比", "field": "P2", "permission": "R", "type": "FLOAT" }, { "name": "红粉3加料百分比", "field": "P3", "permission": "R", "type": "FLOAT" }, { "name": "红粉4加料百分比", "field": "P4", "permission": "R", "type": "FLOAT" }, { "name": "红粉5加料百分比", "field": "P5", "permission": "R", "type": "FLOAT" }, { "name": "卸料百分比", "field": "UNLOAD", "permission": "R", "type": "FLOAT" }, { "name": "桶数", "field": "N_PLTS", "permission": "R", "type": "INT" }, { "name": "当前状态", "field": "current_state", "permission": "R", "type": "INT" }
]

export const DictHM485Dev = [
  //混磨
  { name: "给料双螺旋频率设置", field: "glslx_freq", cmd: "glslxFreqSet", permission: "R/D", type: "FLOAT" },
  { name: "给料双螺旋通讯测试", field: "glslxCommCheck", cmd: "glslxCommCheck", permission: "R/D", type: "INT" },
  {
    "name": "三相电能表电流",
    formatter: "current", "field": "sx_current", "permission": "R", "type": "FLOAT"
  },
  {
    "name": "单相电能表电流",
    formatter: "current", "field": "dx_current", "permission": "R", "type": "FLOAT"
  },
  {
    "name": "给料螺旋电流",
    formatter: "current", "field": "gllx_current", "permission": "R", "type": "FLOAT"
  },
  // {"name":"给料螺旋频率","field":"gllx_freq","permission":"R","type":"FLOAT"},
  {
    "name": "双轴螺旋电流",
    formatter: "current", "field": "szlx_current", "permission": "R", "type": "FLOAT"
  },
  { "name": "双轴螺旋频率", "field": "szlx_freq", "permission": "R", "type": "FLOAT" }
];

export const DictZQ485Dev = [
  { "name": "给料螺旋频率设置", "field": "gllx_freq", "cmd": "gllxFreqSet", "permission": "R/D", "type": "FLOAT" },
  { "name": "双轴螺旋频率设置", "field": "szlx_freq", "cmd": "szlxFreqSet", "permission": "R/D", "type": "FLOAT" },
  {
    "name": "三相电能表电流",
    formatter: "current", "field": "sx_current", "permission": "R", "type": "FLOAT"
  },
  {
    "name": "单相电能表电流",
    formatter: "current", "field": "dx_current", "permission": "R", "type": "FLOAT"
  },
  {
    "name": "给料螺旋电流",
    formatter: "current", "field": "gllx_current", "permission": "R", "type": "FLOAT"
  },
  // {"name":"给料螺旋频率","field":"gllx_freq","permission":"R","type":"FLOAT"},
  {
    "name": "双轴螺旋电流",
    formatter: "current", "field": "szlx_current", "permission": "R", "type": "FLOAT"
  },
  // {"name":"双轴螺旋频率","field":"szlx_freq","permission":"R","type":"FLOAT"}
]

export const DictHMPlc = [
  //混磨
  { name: "给料双螺旋-运行", field: "GLSLX_Sta", internal: "I0.0", type: "BIT" },
  { name: "给料单螺旋-运行", field: "GLDLX_Sta", internal: "I0.1", type: "BIT" },
  { name: "混磨控制-运行", field: "HMKZ_Sta", internal: "I0.2", type: "BIT" },
  { name: "出料螺旋1-运行", field: "CLLX1_Sta", internal: "I0.3", type: "BIT" },
  { name: "出料螺旋2-运行", field: "CLLX2_Sta", internal: "I0.4", type: "BIT" },
  { name: "混料提升机-运行", field: "HLTSJ_Sta", internal: "I0.5", type: "BIT" },
  { name: "备用1-运行", field: "BACKUP1_Sta", internal: "I0.6", type: "BIT" },
  { name: "备用2-运行", field: "BACKUP2_Sta", internal: "I0.7", type: "BIT" },
  { name: "料位计-信号", field: "LWJ_Sig", internal: "I1.0", type: "BIT" },
  { name: "给料单螺旋-故障", field: "GLDLX_Err", internal: "I1.1", type: "BIT" },
  { name: "混磨机-故障", field: "HMJ_Err", internal: "I1.2", type: "BIT" },
  { name: "出料螺旋1-故障", field: "CLLX1_Err", internal: "I1.3", type: "BIT" },
  { name: "出料螺旋2-故障", field: "CLLX2_Err", internal: "I1.4", type: "BIT" },
  { name: "混料提升机-故障", field: "HLTSJ_Err", internal: "I1.5", type: "BIT" },
  { name: "备用1-故障", field: "BACKUP1_Err", internal: "I1.6", type: "BIT" },
  { name: "备用2-故障", field: "BACKUP2_Err", internal: "I1.7", type: "BIT" },
  { name: "远程就地信号", field: "RemoteCtrL_Sig", internal: "I2.7", type: "BIT" },
  {
    name: "给料双螺旋-控制",
    field: "GLSLX_Ctrl",
    internal: "M0.0",
    type: "BIT",
    permission: "R/D",
  },
  {
    name: "给料单螺旋-控制",
    field: "GLDLX_Ctrl",
    internal: "M0.2",
    type: "BIT",
    permission: "R/D",
  },
  {
    name: "混磨-控制",
    field: "HM_Ctrl",
    internal: "M0.4",
    type: "BIT",
    permission: "R/D",
  },
  {
    name: "出料螺旋1-控制",
    field: "CLLX1_Ctrl",
    internal: "M0.6",
    type: "BIT",
    permission: "R/D",
  },
  {
    name: "出料螺旋2-控制",
    field: "CLLX2_Ctrl",
    internal: "M1.0",
    type: "BIT",
    permission: "R/D",
  },
  {
    name: "混料提升机-控制",
    field: "HLTSJ_Ctrl",
    internal: "M1.2",
    type: "BIT",
    permission: "R/D",
  },
  {
    name: "备用1-控制",
    field: "BACKUP1_Ctrl",
    internal: "M1.4",
    type: "BIT",
    permission: "R/D",
  },
  {
    name: "备用2-控制",
    field: "BACKUP2_Ctrl",
    internal: "M1.6",
    type: "BIT",
    permission: "R/D",
  },
  {
    name: "给料单螺旋-电流",
    formatter: "current", field: "GLDLX_Current", internal: "VD50", type: "REAL"
  },
  {
    name: "出料螺旋1-电流",
    formatter: "current", field: "GLLX1_Current", internal: "VD54", type: "REAL"
  },
  {
    name: "出料螺旋2-电流",
    formatter: "current", field: "GLLX2_Current", internal: "VD58", type: "REAL"
  },
  {
    name: "混料提升机-电流",
    formatter: "current", field: "HLTSJ_Current", internal: "VD62", type: "REAL"
  },
  {
    name: "备用1-电流",
    formatter: "current", field: "BACKUP1_Current", internal: "VD66", type: "REAL"
  },
  {
    name: "备用2-电流",
    formatter: "current", field: "BACKUP2_Current", internal: "VD70", type: "REAL"
  },
  {
    name: "软启动器-电流",
    formatter: "current", field: "RQDQ_Current", internal: "VD74", type: "REAL"
  },
];

export const DictZQPlc = [
  { "name": "预加水PID状态", "field": "YJS_WATER_Sta", "internal": "M0.3", "type": "BIT" },
  { "name": "预加水PID报错", "field": "YJS_WATER_Err", "internal": "M0.4", "type": "BIT" },

  { "name": "预加水PID预设值", "field": "YJS_Setpoint", "internal": "VD36", "type": "REAL", permission: "R/D", cmd: "YJS_Setpoint" },
  { "name": "预加水PID/手动切换", "field": "YJS_PID_Auto_Switch", "internal": "M1.0", "type": "BIT", permission: "R/D",cmd: "YJS_PID_Auto_Switch" },
  { "name": "预加水手动模式设置值", "field": "YJS_Manual_Value", "internal": "VD40", "type": "REAL", permission: "R/D", cmd: "YJS_Manual_Value" },
  { "name": "预加水上限设置值", "field": "YJS_Limited_Value_Set", "internal": "VD40", "type": "REAL", permission: "R/D",  cmd: "YJS_Limited_Value_Set" },
  { "name": "预加水恢复PID调控值", "field": "YJS_Recover_Value_Set", "internal": "VD52", "type": "REAL", permission: "R/D",  cmd: "YJS_Recover_Value_Set" },

  { "name": "预加水PID上限0.9报警", "field": "YJS_High_Alarm", "internal": "M1.1", "type": "BIT" },
  { "name": "预加水PID下限0.1报警", "field": "YJS_Low_Alarm", "internal": "M1.2", "type": "BIT" },

  { "name": "造球PID状态", "field": "ZQ_WATER_Sta", "internal": "M0.5", "type": "BIT" },
  { "name": "造球PID报错", "field": "ZQ_WATER_Err", "internal": "M0.6", "type": "BIT" },

  { "name": "造球PID预设值", "field": "ZQ_Setpoint", "internal": "VD44", "type": "REAL", permission: "R/D", cmd: "ZQ_Setpoint" },
  { "name": "造球PID/手动切换", "field": "ZQ_PID_Auto_Switch", "internal": "M1.5", "type": "BIT", permission: "R/D", cmd: "ZQ_PID_Auto_Switch" },
  { "name": "造球手动模式设置值", "field": "ZQ_Manual_Value", "internal": "VD48", "type": "REAL", permission: "R/D", cmd: "ZQ_Manual_Value" },
  { "name": "造球上限设置值", "field": "ZQ_Limited_Value_Set", "internal": "VD60", "type": "REAL", permission: "R/D", cmd: "ZQ_Limited_Value_Set" },
  { "name": "造球恢复PID调控值", "field": "ZQ_Recover_Value_Set", "internal": "VD64", "type": "REAL", permission: "R/D", cmd: "ZQ_Recover_Value_Set" },

  { "name": "造球PID上限0.9报警", "field": "ZQ_High_Alarm", "internal": "M1.5", "type": "BIT" },
  { "name": "造球PID下限0.1报警", "field": "ZQ_Low_Alarm", "internal": "M1.6", "type": "BIT" },



  { "name": "供料螺旋运行", "field": "GLLX_Sta", "internal": "I0.0", "type": "BIT" },
  { "name": "提升机运行", "field": "TSJ_Sta", "internal": "I0.1", "type": "BIT" },
  { "name": "混料双螺旋运行", "field": "HLSLX_Sta", "internal": "I0.2", "type": "BIT" },
  
  { "name": "造球机运行", "field": "ZQJ_Sta", "internal": "I0.3", "type": "BIT" },
  { "name": "刮料机运行", "field": "GLJ_Sta", "internal": "I0.4", "type": "BIT" },
  { "name": "皮带机运行", "field": "PDJ_Sta", "internal": "I0.5", "type": "BIT" },
  { "name": "杂料螺旋运行", "field": "ZLLX_Sta", "internal": "I0.6", "type": "BIT" },
  { "name": "料位计运行", "field": "LWJ_Sta", "internal": "I0.7", "type": "BIT" },
  { "name": "提升机故障", "field": "TSJ_Err", "internal": "I1.1", "type": "BIT" },
  { "name": "混料双螺旋故障", "field": "HLSLX_Err", "internal": "I1.2", "type": "BIT" },
  { "name": "造球机故障", "field": "ZQJ_Err", "internal": "I1.3", "type": "BIT" },
  { "name": "刮料机故障", "field": "GLJ_Err", "internal": "I1.4", "type": "BIT" },
  { "name": "皮带机故障", "field": "PDJ_Err", "internal": "I1.5", "type": "BIT" },
  { "name": "故障备用", "field": "BackUp_Err", "internal": "I1.6", "type": "BIT" },
  { "name": "振动器故障", "field": "ZDQ_Err", "internal": "I1.7", "type": "BIT" },
  { "name": "就地远程信号", "field": "RemoteCtrL_Sig", "internal": "I2.7", "type": "BIT" },
  { "name": "供料螺旋控制", "field": "GLLX_Motor", "internal": "Q0.0", "type": "BIT" },
  { "name": "提升机控制", "field": "TSJ_Motor", "internal": "Q0.1", "type": "BIT" },
  { "name": "混料双螺旋电机", "field": "HLSLX_Motor", "internal": "Q0.2", "type": "BIT" },
  { "name": "造球机电机", "field": "ZQJ_Motor", "internal": "Q0.3", "type": "BIT" },
  { "name": "刮料机电机", "field": "GLJ_Motor", "internal": "Q0.4", "type": "BIT" },
  { "name": "皮带机电机", "field": "PDJ_Motor", "internal": "Q0.5", "type": "BIT" },
  { "name": "杂料螺旋电机", "field": "ZLSLX_Motor", "internal": "Q0.6", "type": "BIT" },
  { "name": "振动器状态", "field": "ZDQ_Sta", "internal": "Q0.7", "type": "BIT" },
  { "name": "一键启动", "field": "Motor_Start", "internal": "M3.0", "type": "BIT" },
  { "name": "一键启动模式", "field": "Motor_Auto_Mode", "internal": "M4.0", "type": "BIT" },
  { "name": "供料螺旋手动启动电机", "field": "GLLX_Manual_Ctrl", "internal": "M5.0", "type": "BIT" },
  { "name": "提升机手动启动电机", "field": "TSJ_Manual_Ctrl", "internal": "M5.2", "type": "BIT" },
  { "name": "混料双螺旋手动启动电机", "field": "HLSLX_Manual_Ctrl", "internal": "M5.4", "type": "BIT" },
  { "name": "造球机手动启动电机", "field": "ZQJ_Manual_Ctrl", "internal": "M5.6", "type": "BIT" },
  { "name": "刮料器手动启动电机", "field": "GLQ_Manual_Ctrl", "internal": "M6.0", "type": "BIT" },
  { "name": "皮带机手动启动电机", "field": "PDJ_Manual_Ctrl", "internal": "M6.2", "type": "BIT" },
  { "name": "杂料螺旋手动启动电机", "field": "ZLLX_Manual_Ctrl", "internal": "M6.4", "type": "BIT" },
  { "name": "振动器手动启动电机", "field": "ZDQ_Manual_Ctrl", "internal": "M6.6", "type": "BIT" },
  {
    "name": "提升机电流",
    formatter: "current", "field": "TSJ_Current", "internal": "VD4", "type": "REAL"
  },
  {
    "name": "刮料器电流",
    formatter: "current", "field": "GLJ_Current", "internal": "VD12", "type": "REAL"
  },
  {
    "name": "皮带机电流",
    formatter: "current", "field": "PDJ_Current", "internal": "VD16", "type": "REAL"
  },
  {
    "name": "振动器电流",
    formatter: "current", "field": "ZDQ_Current", "internal": "VD20", "type": "REAL"
  },
  { "name": "混料双螺旋电流", "field": "HLSLX_Current", "internal": "I0.2", "type": "REAL" },
  { "name": "电控水阀1反馈", "field": "DKSF1FK_Current", "internal": "VD24", "type": "REAL" },
  { "name": "电控水阀2反馈", "field": "DKSF2FK_Current", "internal": "VD28", "type": "REAL" },
  { "name": "电控水阀1输出", "field": "DKSF1FK_Output", "internal": "VW32", "type": "WORD" },
  { "name": "电控水阀2输出", "field": "DKSF2FK_Output", "internal": "VW34", "type": "WORD" },
  { "name": "定时启动时间", "field": "T37_Time_Set", "internal": "VW36", "type": "WORD" },
  { "name": "启动电机数量", "field": "C0_Count_Set", "internal": "VW38", "type": "WORD" },
  { "name": "进料电振机-最大定时", "field": "JL_DZJ_TIM_MAX_Set", "internal": "VW40", "type": "WORD" },
  { "name": "进料电振机-震动定时", "field": "JL_DZJ_TIM_Set", "internal": "VW42", "type": "WORD" },

  { "name": "气锤最大定时设置", "field": "QC_TIM_MAX_Set", "internal": "VW40", "type": "WORD" },
  { "name": "气锤工作时间设置", "field": "QC_TIM_Set", "internal": "VW42", "type": "WORD" },
  
]
